# Generated by Django 3.1.7 on 2022-01-18 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 13, 49, 38, 601555, tzinfo=utc)),
        ),
    ]
